#Config for pipelines.py
PIPELINES:
  DISABLE_RT_LIST: [ 'placeholder' ]
  POPLIST:
    - ID: USER_INPUT #PopList ID
      # List of routines producing to this list (ID = method name)
      # see PopList doc
      PRODUCER:
        - ID: user_input # method_X name
          BUNDLE: SENSOR_BUNDLE #given ID for your class wrapping the method_X
          MT: True # Multithreading producer
      CONSUMER: # List of routines consuming from list
        - ID: list_processor # here method_X as consumer
          BUNDLE: PROCESS_BUNDLE
          MT: True # Multithreading consumer
      IO: pcap_to_mxc
    - ID: PROCESSED_INPUT
      PRODUCER:
        - ID: list_processor # here method_X as producer
          BUNDLE: PROCESS_BUNDLE
          MT: True
      CONSUMER:
        - ID: evaluate
          BUNDLE: EVAL_BUNDLE
          MT: True
      IO: to_pcdet
    - ID: PREDICTIONS
      PRODUCER:
        - ID: evaluate
          BUNDLE: EVAL_BUNDLE
          MT: True
      CONSUMER:
        - ID: Visualization
          BUNDLE: VIZ_BUNDLE
          MT: True
        - ID: ExportLocal
          BUNDLE: UTILS_BUNDLE
          MT: True
        - ID: Statistics
          BUNDLE: STAT_BUNDLE
          MT: True
      IO: pcdet_eval

###       - ID: ExportLocal
#          BUNDLE: UTILS_BUNDLE
#          MT: True
# not supporting multiple context identical threads yet .
# e.g. multiple ExportLocal routines of different values
# might require a work-around