HOST: 135.181.84.173
TCP_PORT: 7501
LIDAR_PORT: 8000
IMU_PORT: 7503
PCAP: '../resources/pcap/OS1-128_Rev-05_Urban-Drive.pcap'
META: '../resources/pcap/OS1-128_Rev-05_Urban-Drive.json'
SAMPLE_RATE: 1 # delay (>=1)
LIST_SIZE: -1 #inf
META_PATH: /metadata # output from live metadata fetching
PCAP_PATH: /pcap # for recordings
N: 5000 # number of samples read (>=1)
BATCH_SIZE: 250 # size of read sensor input slice (>=1)
DELAY: 10 # processed buffer vs input difference to load next batch (>=0)