HOST: 135.181.84.173
TCP_PORT: 7501
LIDAR_PORT: 8000
IMU_PORT: 7503
PCAP: '../resources/pcap/OS1-128_Rev-05_Urban-Drive.pcap'
META: '../resources/pcap/OS1-128_Rev-05_Urban-Drive.json'
SAMPLE_RATE: 0 # delay
LIST_SIZE: -1 #inf
META_PATH: /metadata # output from live metadata fetching
PCAP_PATH: /pcap # for recordings
N: # number of samples read