INIT:
  PLACEHOLDER: NULL
STEPS:
  DISABLED: [ "" ]
  LIST:
    - NAME: "MxCloud2PCDET"
      METHOD: TRIM_SCENE
      CONFIG: #limit box to X (mm) x Y (mm) x Z (mm)
        X: [ -40,30 ]
        Y: [ -40,40 ]
        Z: [ -30,30 ]
  OUTPUT: [ "PCDET" ]